# apps/worker-api/wrangler.toml
name = "worker-api"
main = "./src/index.ts"
compatibility_date = "2024-01-01"

[vars]
TENANT_ID = "com.mrrainbowsmoke" # Default tenant for local dev
TENANT_HOSTNAME_MAP = '{"mrrainbowsmoke.com":"com.mrrainbowsmoke", "rainbowsmokeofficial.com":"com.rainbowsmokeofficial"}'

[[kv_namespaces]]
binding = "KV_TENANT_CONFIG"
id = "00000000000000000000000000000001" # Placeholder ID

[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "ChatSessionDurableObject" # This class will be defined later
